[metadata]
name = "infisical"
description = "CLI for Infisical"
homepage = "https://infisical.com/docs/cli/overview"
version_format = "semver"

[[steps]]
action = "github_archive"
repo = "Infisical/cli"
asset_pattern = "cli_{version}_{os}_{arch}.tar.gz"
strip_dirs = 0
binaries = ["infisical"]

[verify]
command = "infisical --version"
pattern = "{version}"
