package actions

import (
	"os"
	"path/filepath"
	"testing"
)

// -- system_config.go: RequireCommandAction.Preflight with version fields --

func TestRequireCommandAction_Preflight_WithVersionFields(t *testing.T) {
	t.Parallel()
	action := &RequireCommandAction{}

	t.Run("min_version without version_flag", func(t *testing.T) {
		result := action.Preflight(map[string]any{
			"command":     "ls",
			"min_version": "1.0",
		})
		if len(result.Errors) == 0 {
			t.Error("Expected error for min_version without version_flag")
		}
	})

	t.Run("complete version check", func(t *testing.T) {
		result := action.Preflight(map[string]any{
			"command":       "ls",
			"min_version":   "1.0",
			"version_flag":  "--version",
			"version_regex": `(\d+\.\d+)`,
		})
		if len(result.Errors) != 0 {
			t.Errorf("Preflight() errors = %v, want 0", result.Errors)
		}
	})
}

// -- extract.go: Preflight with different format values --

func TestExtractAction_Preflight_ValidFormats(t *testing.T) {
	t.Parallel()
	action := &ExtractAction{}

	formats := []string{"tar.gz", "tar.xz", "tar.bz2", "tar.zst", "tar.lz", "tar", "zip"}
	for _, f := range formats {
		result := action.Preflight(map[string]any{
			"archive": "test." + f,
			"format":  f,
		})
		if len(result.Errors) != 0 {
			t.Errorf("Preflight() with format %q errors = %v", f, result.Errors)
		}
	}
}

// -- install_binaries.go: Preflight with various params --

func TestInstallBinariesAction_Preflight_WithParams(t *testing.T) {
	t.Parallel()
	action := &InstallBinariesAction{}

	t.Run("valid string list", func(t *testing.T) {
		result := action.Preflight(map[string]any{
			"binaries": []any{"bin/tool"},
		})
		if len(result.Errors) != 0 {
			t.Errorf("Preflight() errors = %v", result.Errors)
		}
	})

	t.Run("valid map format", func(t *testing.T) {
		result := action.Preflight(map[string]any{
			"binaries": map[string]any{"src/tool": "tool"},
		})
		if len(result.Errors) != 0 {
			t.Errorf("Preflight() errors = %v", result.Errors)
		}
	})
}

// -- configure_make.go: touchAutogeneratedFiles with full autotools file set --

func TestTouchAutogeneratedFiles_FullSet(t *testing.T) {
	t.Parallel()
	tmpDir := t.TempDir()

	subDir := filepath.Join(tmpDir, "subdir")
	if err := os.MkdirAll(subDir, 0755); err != nil {
		t.Fatal(err)
	}

	autoFiles := []string{
		"configure",
		"configure.ac",
		"Makefile.in",
		"Makefile.am",
		"aclocal.m4",
		"config.h.in",
		"ltmain.sh",
	}
	for _, f := range autoFiles {
		if err := os.WriteFile(filepath.Join(tmpDir, f), []byte("content"), 0644); err != nil {
			t.Fatal(err)
		}
	}

	touchAutogeneratedFiles(tmpDir)

	// Verify files still exist
	for _, f := range autoFiles {
		if _, err := os.Stat(filepath.Join(tmpDir, f)); os.IsNotExist(err) {
			t.Errorf("File %s disappeared after touchAutogeneratedFiles", f)
		}
	}
}

// -- extract.go: Preflight missing archive --

func TestExtractAction_Preflight_MissingArchive(t *testing.T) {
	t.Parallel()
	action := &ExtractAction{}
	result := action.Preflight(map[string]any{
		"format": "tar.gz",
	})
	if len(result.Errors) == 0 {
		t.Error("Expected error for missing archive")
	}
}

// -- chmod.go: Preflight --

func TestChmodAction_Preflight_MissingFiles(t *testing.T) {
	t.Parallel()
	action := &ChmodAction{}
	result := action.Preflight(map[string]any{})
	if len(result.Errors) == 0 {
		t.Error("Expected error for missing files param")
	}
}

func TestChmodAction_Preflight_Valid(t *testing.T) {
	t.Parallel()
	action := &ChmodAction{}
	result := action.Preflight(map[string]any{
		"files": []any{"bin/tool"},
	})
	if len(result.Errors) != 0 {
		t.Errorf("Preflight() errors = %v", result.Errors)
	}
}

// -- run_command.go: Preflight --

func TestRunCommandAction_Preflight_Additional(t *testing.T) {
	t.Parallel()
	action := &RunCommandAction{}

	t.Run("missing command", func(t *testing.T) {
		result := action.Preflight(map[string]any{})
		if len(result.Errors) == 0 {
			t.Error("Expected error for missing command")
		}
	})

	t.Run("valid", func(t *testing.T) {
		result := action.Preflight(map[string]any{
			"command": "echo hello",
		})
		if len(result.Errors) != 0 {
			t.Errorf("Preflight() errors = %v", result.Errors)
		}
	})
}

// -- require_system.go: Preflight --

func TestRequireSystemAction_Preflight_Additional(t *testing.T) {
	t.Parallel()
	action := &RequireSystemAction{}

	t.Run("valid", func(t *testing.T) {
		result := action.Preflight(map[string]any{
			"command": "dpkg",
		})
		if len(result.Errors) != 0 {
			t.Errorf("Preflight() errors = %v", result.Errors)
		}
	})

	t.Run("missing command", func(t *testing.T) {
		result := action.Preflight(map[string]any{})
		if len(result.Errors) == 0 {
			t.Error("Expected error for missing command")
		}
	})
}
