[metadata]
  name = "cargo-release"
  description = "Cargo subcommand for you to smoothly release rust crates"
  homepage = "https://github.com/crate-ci/cargo-release"
  version_format = "semver"

[[steps]]
  action = "github_archive"
  repo = "crate-ci/cargo-release"
  asset_pattern = "cargo-release-v{version}-{arch}-{os}.tar.gz"
  strip_dirs = 0
  binaries = ["cargo-release"]
  os_mapping = { linux = "unknown-linux-musl", darwin = "apple-darwin" }
  arch_mapping = { amd64 = "x86_64", arm64 = "aarch64" }

[verify]
  command = "cargo-release release --version"
  pattern = "cargo-release {version}"
