[metadata]
name = "cargo-edit"
description = "Cargo commands for modifying a `Cargo.toml` file.."
homepage = "https://github.com/killercup/cargo-edit"

[version]
source = "crates_io"

[[steps]]
action = "cargo_install"
crate = "cargo-edit"
executables = ["cargo-add", "cargo-rm", "cargo-upgrade", "cargo-set-version"]

[verify]
command = "cargo add --version"
pattern = "{version}"
