[metadata]
  name = "dbus"
  description = "Message bus system, providing inter-application communication"
  homepage = "https://wiki.freedesktop.org/www/Software/dbus"
  version_format = ""
  requires_sudo = false
  tier = 0
  type = ""
  llm_validation = "skipped"

[version]
  source = ""
  github_repo = ""
  tag_prefix = ""
  module = ""
  formula = ""
  cask = ""
  tap = ""
  fossil_repo = ""
  project_name = ""
  version_separator = ""
  timeline_tag = ""

[[steps]]
  action = "homebrew"
  formula = "dbus"

[[steps]]
  action = "install_binaries"
  binaries = ["bin/dbus-cleanup-sockets", "bin/dbus-daemon", "bin/dbus-launch", "bin/dbus-monitor", "bin/dbus-run-session", "bin/dbus-send", "bin/dbus-test-tool", "bin/dbus-update-activation-environment", "bin/dbus-uuidgen"]

[verify]
  command = "dbus-cleanup-sockets --version"
  pattern = ""
