[metadata]
  name = "b3sum"
  description = "a command line implementation of the BLAKE3 hash function"
  homepage = "https://github.com/BLAKE3-team/BLAKE3"
  version_format = ""
  requires_sudo = false
  tier = 0
  type = ""

[version]
  source = ""
  github_repo = ""
  tag_prefix = ""
  module = ""
  formula = ""
  cask = ""
  tap = ""
  fossil_repo = ""
  project_name = ""
  version_separator = ""
  timeline_tag = ""

[[steps]]
  action = "cargo_install"
  crate = "b3sum"
  executables = ["b3sum"]

[verify]
  command = "b3sum --version"
  pattern = "{version}"
