[metadata]
name = "shfmt"
description = "Shell script formatter"
homepage = "https://github.com/mvdan/sh"
version_format = "semver"
curated = true

[version]
github_repo = "mvdan/sh"
tag_prefix = "v"

[[steps]]
action = "github_file"
repo = "mvdan/sh"
asset_pattern = "shfmt_v{version}_{os}_{arch}"
binaries = [{src = "shfmt_v{version}_{os}_{arch}", dest = "bin/shfmt"}]

[verify]
command = "shfmt --version"
pattern = "{version}"
