[metadata]
  name = "probe-rs-tools"
  description = "A collection of on chip debugging tools to communicate with microchips."
  homepage = "https://probe.rs"
  version_format = "semver"
  supported_libc = ["glibc"]

[[steps]]
  action = "github_archive"
  repo = "probe-rs/probe-rs"
  asset_pattern = "probe-rs-tools-{arch}-{os}.tar.xz"
  strip_dirs = 1
  binaries = ["cargo-embed", "cargo-flash", "probe-rs"]
  os_mapping = { linux = "unknown-linux-gnu", darwin = "apple-darwin" }
  arch_mapping = { amd64 = "x86_64", arm64 = "aarch64" }

[verify]
  command = "probe-rs --version"
  pattern = "{version}"
