[metadata]
  name = "maturin"
  description = "Build and publish crates with pyo3, cffi and uniffi bindings as well as rust binaries as python packages"
  homepage = "https://github.com/pyo3/maturin"
  version_format = "semver"

[version]
  tag_prefix = "v"

[[steps]]
  action = "github_archive"
  repo = "PyO3/maturin"
  asset_pattern = "maturin-{arch}-{os}.tar.gz"
  strip_dirs = 0
  binaries = ["maturin"]
  os_mapping = { darwin = "apple-darwin", linux = "unknown-linux-musl" }
  arch_mapping = { amd64 = "x86_64", arm64 = "aarch64" }

[verify]
  command = "maturin --version"
  pattern = "{version}"
