[metadata]
  name = "liblqr"
  description = "C/C++ seam carving library"
  homepage = "https://liblqr.wikidot.com/"
  version_format = ""
  requires_sudo = false
  runtime_dependencies = ["glib", "gettext"]
  tier = 0
  type = "library"
  llm_validation = "skipped"

[version]
  source = ""
  github_repo = ""
  tag_prefix = ""
  module = ""
  formula = ""
  cask = ""
  tap = ""
  fossil_repo = ""
  project_name = ""
  version_separator = ""
  timeline_tag = ""

[[steps]]
  action = "homebrew"
  formula = "liblqr"
  [steps.when]
    libc = ["glibc"]
    os = ["linux"]

[[steps]]
  action = "install_binaries"
  install_mode = "directory"
  outputs = ["lib/liblqr-1.so", "lib/liblqr-1.so.0", "lib/liblqr-1.so.0.3.2", "lib/pkgconfig/lqr-1.pc", "include/lqr-1/lqr/lqr_base.h", "include/lqr-1/lqr/lqr_carver_bias_pub.h", "include/lqr-1/lqr/lqr_carver_list_pub.h", "include/lqr-1/lqr/lqr_carver_pub.h", "include/lqr-1/lqr/lqr_carver_rigmask_pub.h", "include/lqr-1/lqr/lqr_cursor_pub.h", "include/lqr-1/lqr/lqr_energy_pub.h", "include/lqr-1/lqr/lqr_gradient_pub.h", "include/lqr-1/lqr/lqr_progress_pub.h", "include/lqr-1/lqr/lqr_rwindow_pub.h", "include/lqr-1/lqr/lqr_vmap_list_pub.h", "include/lqr-1/lqr/lqr_vmap_pub.h", "include/lqr-1/lqr.h"]
  [steps.when]
    libc = ["glibc"]
    os = ["linux"]

[[steps]]
  action = "homebrew"
  formula = "liblqr"
  [steps.when]
    os = ["darwin"]

[[steps]]
  action = "install_binaries"
  install_mode = "directory"
  outputs = ["lib/liblqr-1.0.dylib", "lib/liblqr-1.dylib", "lib/pkgconfig/lqr-1.pc", "include/lqr-1/lqr/lqr_base.h", "include/lqr-1/lqr/lqr_carver_bias_pub.h", "include/lqr-1/lqr/lqr_carver_list_pub.h", "include/lqr-1/lqr/lqr_carver_pub.h", "include/lqr-1/lqr/lqr_carver_rigmask_pub.h", "include/lqr-1/lqr/lqr_cursor_pub.h", "include/lqr-1/lqr/lqr_energy_pub.h", "include/lqr-1/lqr/lqr_gradient_pub.h", "include/lqr-1/lqr/lqr_progress_pub.h", "include/lqr-1/lqr/lqr_rwindow_pub.h", "include/lqr-1/lqr/lqr_vmap_list_pub.h", "include/lqr-1/lqr/lqr_vmap_pub.h", "include/lqr-1/lqr.h"]
  [steps.when]
    os = ["darwin"]
