[metadata]
  name = "libogg"
  description = "Ogg Bitstream Library"
  homepage = "https://www.xiph.org/ogg/"
  version_format = ""
  requires_sudo = false
  tier = 0
  type = "library"
  llm_validation = "skipped"

[version]
  source = "homebrew"
  github_repo = ""
  tag_prefix = ""
  module = ""
  formula = "libogg"
  cask = ""
  tap = ""
  fossil_repo = ""
  project_name = ""
  version_separator = ""
  timeline_tag = ""

[[steps]]
  action = "homebrew"
  formula = "libogg"
  [steps.when]
    libc = ["glibc"]
    os = ["linux"]

[[steps]]
  action = "install_binaries"
  install_mode = "directory"
  outputs = ["lib/libogg.a", "lib/libogg.so", "lib/libogg.so.0", "lib/libogg.so.0.8.6", "lib/pkgconfig/ogg.pc", "include/ogg/config_types.h", "include/ogg/ogg.h", "include/ogg/os_types.h"]
  [steps.when]
    libc = ["glibc"]
    os = ["linux"]

[[steps]]
  action = "homebrew"
  formula = "libogg"
  [steps.when]
    os = ["darwin"]

[[steps]]
  action = "install_binaries"
  install_mode = "directory"
  outputs = ["lib/libogg.0.8.6.dylib", "lib/libogg.0.dylib", "lib/libogg.a", "lib/libogg.dylib", "lib/pkgconfig/ogg.pc", "include/ogg/config_types.h", "include/ogg/ogg.h", "include/ogg/os_types.h"]
  [steps.when]
    os = ["darwin"]
