[metadata]
  name = "komac"
  description = "A manifest creator for winget-pkgs"
  homepage = "https://github.com/russellbanks/Komac"
  version_format = "semver"
  supported_libc = ["glibc"]

[version]
  github_repo = ""

[[steps]]
  action = "github_archive"
  repo = "russellbanks/Komac"
  asset_pattern = "komac-{version}-{arch}-{os}.tar.gz"
  strip_dirs = 0
  binaries = ["komac"]
  os_mapping = { linux = "unknown-linux-gnu", darwin = "apple-darwin" }
  arch_mapping = { amd64 = "x86_64", arm64 = "aarch64" }

[verify]
  command = "komac --version"
  pattern = "{version}"
